[connections.postgresql]
url = "postgresql://postgres:postgres@localhost:5432/productos"

[credentials]
# Estructura: "usuario" = "contraseña"
admin = "admin123"
luty = "clave456"
vendedor1 = "ventas789"