[connections.postgresql]
url = "postgresql://postgres:postgres@localhost:5432/productos"

[credentials]
luty = { password = "123", role = "admin" }
jorge = { password = "123", role = "admin" }
hugo = { password = "456", role = "vendedor" }